### ISSUE TITLE
Document deployment patterns & configuration

### ISSUE THREAD

**Issue by nonword** [NYPL/engineering-general#66]
I'd like to continue the discussion started in https://github.com/NYPL-discovery/discovery-api/pull/93 , which proposed placing common deployment config in a central place like engineering-general. There are several patterns for deployment emerging from our work, with lots of common config. I like @nodanaonlyzuul's idea that we collect that information in a central place, perhaps organized by technology (e.g. EB, lambda, EKS). For any kind of deployment, we could document the distinct strategies we consider best practice and link to a boilerplate repo, yeoman generator, etc. This would help bring up new apps, but could also allow us to slim down our READMEs by letting us link directly to the deployment standard the app uses, reducing the app's own responsibility for documenting all of the relevant `eb` subcommands, for example. (Separately, but in that same spirit, I'd love for us to develop a vocabulary of git deploy strategies to make it easier to read at a glance what kind of app we're dealing with.)

**Comment by LucasCioffi** [comment]
@nodanaonlyzuul @nonword if either of you would like to co-draft a rough Google Doc to think through some of this, I'd be happy to participate.

**Comment by nodanaonlyzuul** [comment]
Maybe we can chat about this over lunch this week?

**Comment by holingpoon** [comment]
Been working on documenting Travis CI and what it does for deployment to Elastic Beanstalk. No PR yet as the instructions may get a little long.
https://github.com/NYPL/engineering-general/blob/travis-ci/standards/travis-ci.md

**Comment by nonword** [comment]
That's looking great, ho-ling. I've been trying to work out the best way to store travis-encrypted aws creds in .travis.yml. This is the stub documentation I've come up with. Is this more or less how we've been storing creds in other apps you've seen?

___________________
To configure Travis to deploy to EB:

 - If you haven't already, log in to Github through travis:
    ```
     travis login --org
    ```
 - Look up access keys and secrets for each AWS account you'll want to deploy to. Use low-privilege accounts where possible (e.g. nypl-sandbox "travis-deployer" account)
 - Add encrypted KEY and SECRET variables to `.travis.yml` (note that if you're deploying to multiple AWS accounts, it may be useful to add account suffixes to differentiate pairs, like "_DEVELOPMENT" below):
   ```
    travis encrypt AWS_ACCESS_KEY_ID_DEVELOPMENT=[travis-deployer key id] --add
    travis encrypt AWS_SECRET_ACCESS_KEY_DEVELOPMENT=[travis-deployer secret] --add
   ```
 - Add `deploy` entries to `.travis.yml` for each deploy hook, e.g.:
   ```
    deploy:
     - provider: elasticbeanstalk
       skip_cleanup: true
       access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
       secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
       region: us-east-1
       app: discovery-api
       env: discovery-api-dev
       bucket_name: elasticbeanstalk-us-east-1-224280085904
       bucket_path: discovery-api-dev
       on:
         repo: NYPL-discovery/discovery-api
         branch: development
    ```
